// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ssLC
std::vector<std::string> ssLC(int I1, int I2, std::vector<std::string> line, std::string sep);
RcppExport SEXP CoFRA_ssLC(SEXP I1SEXP, SEXP I2SEXP, SEXP lineSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type I1(I1SEXP);
    Rcpp::traits::input_parameter< int >::type I2(I2SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type line(lineSEXP);
    Rcpp::traits::input_parameter< std::string >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(ssLC(I1, I2, line, sep));
    return rcpp_result_gen;
END_RCPP
}
