# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return subString for each item in list
#'
#' @param I1 integer
#' @param I2 integer
#' @param line string
#' @param sep string
#' @export
ssLC <- function(I1, I2, line, sep) {
    .Call('CoFRA_ssLC', PACKAGE = 'CoFRA', I1, I2, line, sep)
}

